version: '3.1'

services:
  mariadb:
    image: mysql:8.0
    container_name: mysql-restful-api-golang
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mysql_restful_api_golang
    - MYSQL_USER=mybatis
    - MYSQL_PASSWORD=mybatis
#    - TZ=Asia/Seoul
    volumes:
    - ${HOME}/data/docker/mysql_restful_api_golang:/var/lib/mysql
#    command:
#    - "mysqld"
#    - "--character-set-server=utf8mb4"
#    - "--collation-server=utf8mb4_unicode_ci"
    ports:
    - 3306:3306