### 사용자 등록
POST http://localhost:8080/api/v1/register
Accept: application/json

{
	"Name": "Joe Bloke2",
	"Username": "test2@fake-domain.com",
    "Password": "secret"
}

### 사용자 로그인
POST http://localhost:8080/api/v1/login
Accept: application/json

{
  "Username": "test2@fake-domain.com",
  "Password": "secret"
}


### 사용자 목록 조회
GET http://localhost:8080/api/v1/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjEyMDAwMDAwMDAwMDAsInVzZXJuYW1lIjoidGVzdDJAZmFrZS1kb21haW4uY29tIn0.DA60DpQYF6j-nCwkXNYu9sag7qg1rktuCWU7bohe154
###
